/**
 * Curated 3D fractal library. Each entry is a named parameter set
 * on a real DE family so looks actually differ.
 */

export const FAMILY = {
  MANDELBULB: 0,
  JULIA: 1,
  MANDELBOX: 2,
  MENGER: 3,
  SIERPINSKI: 4,
  KIFS: 5,
  HYBRID: 6,
  QUAT: 7,
  APOLLO: 8,
  OCTA: 9,
  ABSBULB: 10,
  KLEIN: 11,
  TETRABROT: 12,
  CUSTOM: 13,
};

export const CATEGORIES = [
  { id: "all", label: "All" },
  { id: "bulbs", label: "Bulbs" },
  { id: "julia", label: "Julia" },
  { id: "boxes", label: "Boxes" },
  { id: "sponges", label: "Sponges" },
  { id: "stars", label: "Stars" },
  { id: "hybrids", label: "Hybrids" },
  { id: "worlds", label: "Worlds" },
];

export const FAMILY_KNOBS = {
  0: ["power", "iterations", "bailout", "scale", "offset", "rotate"],
  1: ["power", "iterations", "bailout", "julia", "offset", "rotate"],
  2: ["scale", "iterations", "fold", "minRadius", "offset", "rotate"],
  3: ["iterations", "scale", "offset", "rotate"],
  4: ["iterations", "scale", "offset", "rotate"],
  5: ["iterations", "scale", "fold", "rotate", "offset", "julia"],
  6: ["power", "iterations", "scale", "fold", "julia", "offset", "rotate"],
  7: ["iterations", "bailout", "julia", "scale", "minRadius", "rotate"],
  8: ["iterations", "scale", "fold", "offset", "rotate"],
  9: ["iterations", "scale", "offset", "rotate"],
  10: ["power", "iterations", "bailout", "julia", "offset", "rotate"],
  11: ["iterations", "scale", "fold", "minRadius", "offset", "rotate"],
  12: ["power", "iterations", "bailout", "scale", "offset", "rotate"],
  13: ["power", "iterations", "bailout", "scale", "offset", "julia", "rotate", "fold"],
};

export const CATALOG = [
  { id: "classic-bulb", name: "Classic Mandelbulb", family: 0, category: "bulbs", blurb: "The famous 3-D cousin of the Mandelbrot set. A star-fruit planet with endless dimples.", params: { power: 8, iterations: 8, bailout: 2, scale: 1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 0, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.8 }, cam: { dist: 2.8, elev: 0.28, azim: -0.45 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "peanut-bulb", name: "Peanut Bulb", family: 0, category: "bulbs", blurb: "Power 2 makes two chubby lobes, like a space peanut.", params: { power: 2, iterations: 10, bailout: 4, scale: 1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 7, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.1 }, cam: { dist: 3.1, elev: 0.15, azim: 0.4 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "cubic-bulb", name: "Cubic Bulb", family: 0, category: "bulbs", blurb: "Three-fold bumps. Softer than the classic, a little like a rounded clover.", params: { power: 3, iterations: 9, bailout: 2, scale: 1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 3, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.9 }, cam: { dist: 2.9, elev: 0.35, azim: 0.8 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "quart-bulb", name: "Quartet Bulb", family: 0, category: "bulbs", blurb: "Power 4 pulls four fat ridges. Think of a squishy pyramid cluster.", params: { power: 4, iterations: 8, bailout: 2, scale: 1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 1, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.7 }, cam: { dist: 2.7, elev: 0.2, azim: -1.0 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "penta-bulb", name: "Penta Bulb", family: 0, category: "bulbs", blurb: "Five-way symmetry. A sea-star that grew a brain.", params: { power: 5, iterations: 8, bailout: 2, scale: 1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 2, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.75 }, cam: { dist: 2.75, elev: 0.4, azim: 1.2 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "hex-bulb", name: "Hex Bulb", family: 0, category: "bulbs", blurb: "Six ridges wrap the globe. A snowflake planet.", params: { power: 6, iterations: 8, bailout: 2, scale: 1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 6, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.7 }, cam: { dist: 2.7, elev: 0.22, azim: 0.2 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "lucky-seven", name: "Lucky Seven Bulb", family: 0, category: "bulbs", blurb: "Power 7 is almost classic, but a bit more crowded and leafy.", params: { power: 7, iterations: 8, bailout: 2, scale: 1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.65 }, cam: { dist: 2.65, elev: 0.3, azim: -0.9 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "niner", name: "Niner Spikes", family: 0, category: "bulbs", blurb: "Nine-fold spikes. Sharper than eight, still friendly.", params: { power: 9, iterations: 8, bailout: 2, scale: 1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 5, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.6 }, cam: { dist: 2.6, elev: 0.18, azim: 0.55 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "deca-bulb", name: "Deca Bulb", family: 0, category: "bulbs", blurb: "Ten ridges. Looks like a sea urchin that learned math.", params: { power: 10, iterations: 8, bailout: 2, scale: 1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 8, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.55 }, cam: { dist: 2.55, elev: 0.32, azim: 1.5 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "dozen-bulb", name: "Dozen Spikes", family: 0, category: "bulbs", blurb: "Power 12 packs lots of thin spikes. Great for glow.", params: { power: 12, iterations: 7, bailout: 2, scale: 1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 8, glow: 0.7, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.5 }, cam: { dist: 2.5, elev: 0.25, azim: -0.2 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "spiky-sun", name: "Spiky Sun", family: 0, category: "bulbs", blurb: "Power 16 is extra pointy \u2014 a tiny sun with needles.", params: { power: 16, iterations: 7, bailout: 2, scale: 1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 5, glow: 0.85, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.4 }, cam: { dist: 2.4, elev: 0.12, azim: 0.7 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "soft-bulb", name: "Soft Clay Bulb", family: 0, category: "bulbs", blurb: "Fewer repeats make a puffier, clay-like bulb.", params: { power: 8, iterations: 4, bailout: 2, scale: 1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 1, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.9 }, cam: { dist: 2.9, elev: 0.2, azim: -0.3 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "deep-bulb", name: "Deep Detail Bulb", family: 0, category: "bulbs", blurb: "More repeats carve finer cracks. Costs a bit of speed.", params: { power: 8, iterations: 12, bailout: 2, scale: 1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 0, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 110, camDist: 2.6 }, cam: { dist: 2.6, elev: 0.35, azim: 0.15 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "tilted-bulb", name: "Tilted Bulb", family: 0, category: "bulbs", blurb: "A gentle twist so the poles are not straight up.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.7, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 2, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.8 }, cam: { dist: 2.8, elev: 0.45, azim: -0.6 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "shifted-bulb", name: "Shifted Heart", family: 0, category: "bulbs", blurb: "Nudge the center and the lobes grow uneven, like a lopsided heart.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.18, offsetY: -0.06, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.7 }, cam: { dist: 2.7, elev: 0.2, azim: 0.9 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "mini-bulb", name: "Pocket Bulb", family: 0, category: "bulbs", blurb: "Scale up the math so the whole set shrinks into a denser marble.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.45, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 7, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.2 }, cam: { dist: 2.2, elev: 0.25, azim: -0.4 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "wide-bulb", name: "Wide Horizon Bulb", family: 0, category: "bulbs", blurb: "A bigger bailout lets the outer shells puff farther out.", params: { power: 8, iterations: 8, bailout: 8, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 6, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.2 }, cam: { dist: 3.2, elev: 0.15, azim: 0.3 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "tight-bulb", name: "Tight Shell Bulb", family: 0, category: "bulbs", blurb: "A small bailout clips the set into a tighter pod.", params: { power: 8, iterations: 9, bailout: 1.4, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 9, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.5 }, cam: { dist: 2.5, elev: 0.3, azim: -1.1 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "gold-bulb", name: "Gold Relic", family: 0, category: "bulbs", blurb: "Same classic bulb wearing a gold-and-bronze coat.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 7, glow: 0.5, softShadow: 0.85, ao: 0.8, exposure: 1.4, maxSteps: 90, camDist: 2.75 }, cam: { dist: 2.75, elev: 0.22, azim: 1.1 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "ice-bulb", name: "Ice Cathedral Bulb", family: 0, category: "bulbs", blurb: "Cool blues, higher glow \u2014 a frozen palace.", params: { power: 8, iterations: 9, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 6, glow: 0.75, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.7 }, cam: { dist: 2.7, elev: 0.4, azim: -0.15 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "julia-coral", name: "Coral Julia", family: 1, category: "julia", blurb: "A Julia bulb: the seed stays put, so arms grow like coral.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.2, juliaY: 0.4, juliaZ: 0.15, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.4 }, cam: { dist: 2.4, elev: 0.2, azim: 0.5 }, show: [ "power", "iterations", "bailout", "offset", "julia", "rotate" ] },
  { id: "julia-twin", name: "Twin Julia", family: 1, category: "julia", blurb: "Two fat islands linked by a thin bridge.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.35, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 1, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.6 }, cam: { dist: 2.6, elev: 0.1, azim: -0.8 }, show: [ "power", "iterations", "bailout", "offset", "julia", "rotate" ] },
  { id: "julia-needle", name: "Needle Julia", family: 1, category: "julia", blurb: "A skinny seed stretches the set into needles.", params: { power: 8, iterations: 9, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.65, juliaZ: 0.05, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 8, glow: 0.6, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.3 }, cam: { dist: 2.3, elev: 0.35, azim: 1.3 }, show: [ "power", "iterations", "bailout", "offset", "julia", "rotate" ] },
  { id: "julia-spiral", name: "Spiral Julia", family: 1, category: "julia", blurb: "A seed off to the side winds the ridges into a swirl.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.4, juliaX: 0.22, juliaY: 0.28, juliaZ: -0.1, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 0, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.45 }, cam: { dist: 2.45, elev: 0.25, azim: 0.2 }, show: [ "power", "iterations", "bailout", "offset", "julia", "rotate" ] },
  { id: "julia-soft", name: "Pudding Julia", family: 1, category: "julia", blurb: "Low power + mild seed = a pudding blob with dimples.", params: { power: 3, iterations: 10, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.4, juliaY: 0.1, juliaZ: 0.2, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.8 }, cam: { dist: 2.8, elev: 0.18, azim: -0.5 }, show: [ "power", "iterations", "bailout", "offset", "julia", "rotate" ] },
  { id: "julia-firefly", name: "Firefly Julia", family: 1, category: "julia", blurb: "High glow and a neon palette. Little lights hide in the folds.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.15, juliaY: -0.35, juliaZ: 0.25, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 8, glow: 0.95, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.35 }, cam: { dist: 2.35, elev: 0.3, azim: 0.9 }, show: [ "power", "iterations", "bailout", "offset", "julia", "rotate" ] },
  { id: "julia-ribbon", name: "Ribbon Julia", family: 1, category: "julia", blurb: "Power 4 with a sideways seed makes ribbon sheets.", params: { power: 4, iterations: 9, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.45, juliaY: 0.15, juliaZ: -0.2, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 5, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.5 }, cam: { dist: 2.5, elev: 0.12, azim: -1.2 }, show: [ "power", "iterations", "bailout", "offset", "julia", "rotate" ] },
  { id: "julia-crystal", name: "Crystal Julia", family: 1, category: "julia", blurb: "Icy palette and a tight seed. Looks carved from glass.", params: { power: 8, iterations: 9, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.1, juliaY: -0.5, juliaZ: 0.1, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 6, glow: 0.55, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.4 }, cam: { dist: 2.4, elev: 0.4, azim: 0.4 }, show: [ "power", "iterations", "bailout", "offset", "julia", "rotate" ] },
  { id: "julia-broken", name: "Broken Crown", family: 1, category: "julia", blurb: "A large seed shatters the bulb into a broken crown.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.55, juliaY: 0.4, juliaZ: 0.3, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 7, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.7 }, cam: { dist: 2.7, elev: 0.22, azim: -0.25 }, show: [ "power", "iterations", "bailout", "offset", "julia", "rotate" ] },
  { id: "julia-deep", name: "Deep Julia Well", family: 1, category: "julia", blurb: "Many repeats dig tunnels into the seed.", params: { power: 8, iterations: 12, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.25, juliaY: 0.2, juliaZ: -0.25, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 2, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 110, camDist: 2.2 }, cam: { dist: 2.2, elev: 0.15, azim: 1.0 }, show: [ "power", "iterations", "bailout", "offset", "julia", "rotate" ] },
  { id: "julia-p2", name: "Peanut Julia", family: 1, category: "julia", blurb: "Power-2 Julia: two dancing blobs sharing a glow.", params: { power: 2, iterations: 12, bailout: 4, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.4, juliaY: 0.5, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 1, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.9 }, cam: { dist: 2.9, elev: 0.1, azim: 0.6 }, show: [ "power", "iterations", "bailout", "offset", "julia", "rotate" ] },
  { id: "julia-p16", name: "Starburst Julia", family: 1, category: "julia", blurb: "High power + Julia seed = a starburst of thin rays.", params: { power: 16, iterations: 7, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.1, juliaY: 0.3, juliaZ: 0.15, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 5, glow: 0.8, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.2 }, cam: { dist: 2.2, elev: 0.2, azim: -0.7 }, show: [ "power", "iterations", "bailout", "offset", "julia", "rotate" ] },
  { id: "julia-shift", name: "Wander Julia", family: 1, category: "julia", blurb: "Offset plus seed \u2014 the whole island drifts off-center.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.12, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.2, juliaY: -0.15, juliaZ: 0.35, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 3, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.55 }, cam: { dist: 2.55, elev: 0.28, azim: 0.15 }, show: [ "power", "iterations", "bailout", "offset", "julia", "rotate" ] },
  { id: "julia-mono", name: "Ink Julia", family: 1, category: "julia", blurb: "A monochrome Julia, good for studying the sculpture.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.3, juliaY: 0.25, juliaZ: 0.05, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 9, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.5 }, cam: { dist: 2.5, elev: 0.25, azim: -0.9 }, show: [ "power", "iterations", "bailout", "offset", "julia", "rotate" ] },
  { id: "classic-box", name: "Classic Mandelbox", family: 2, category: "boxes", blurb: "Box folds and sphere folds build a cubist city of rooms.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 9, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 100, camDist: 5.5 }, cam: { dist: 5.5, elev: 0.35, azim: 0.5 }, show: [ "scale", "iterations", "fold", "minRadius", "offset", "rotate" ] },
  { id: "tiny-box", name: "Tiny Rooms", family: 2, category: "boxes", blurb: "A smaller scale packs rooms tighter, like a dollhouse labyrinth.", params: { power: 8.0, iterations: 9, bailout: 2.0, scale: 1.6, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 2, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 4.8 }, cam: { dist: 4.8, elev: 0.28, azim: -0.7 }, show: [ "scale", "iterations", "fold", "minRadius", "offset", "rotate" ] },
  { id: "huge-box", name: "Huge Hangar", family: 2, category: "boxes", blurb: "Bigger scale stretches halls into giant hangars.", params: { power: 8.0, iterations: 7, bailout: 2.0, scale: 2.4, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 7, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 6.5 }, cam: { dist: 6.5, elev: 0.4, azim: 0.2 }, show: [ "scale", "iterations", "fold", "minRadius", "offset", "rotate" ] },
  { id: "neg-box", name: "Inside-Out Box", family: 2, category: "boxes", blurb: "Negative scale flips insides out. A cave that is also a castle.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: -1.5, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 0, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 5.0 }, cam: { dist: 5.0, elev: 0.22, azim: 1.1 }, show: [ "scale", "iterations", "fold", "minRadius", "offset", "rotate" ] },
  { id: "deep-neg", name: "Deep Inversion", family: 2, category: "boxes", blurb: "Scale \u22122 digs a deeper inverted city.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: -2.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.45, fixedRadius: 1.0, palette: 8, glow: 0.5, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 5.2 }, cam: { dist: 5.2, elev: 0.3, azim: -0.4 }, show: [ "scale", "iterations", "fold", "minRadius", "offset", "rotate" ] },
  { id: "folded-city", name: "Folded City", family: 2, category: "boxes", blurb: "A wider fold slaps walls farther apart.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.4, minRadius: 0.5, fixedRadius: 1.0, palette: 1, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 6.0 }, cam: { dist: 6.0, elev: 0.38, azim: 0.8 }, show: [ "scale", "iterations", "fold", "minRadius", "offset", "rotate" ] },
  { id: "tight-fold", name: "Tight Fold Box", family: 2, category: "boxes", blurb: "A small fold squeezes everything toward the middle.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 0.65, minRadius: 0.5, fixedRadius: 1.0, palette: 5, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 4.6 }, cam: { dist: 4.6, elev: 0.2, azim: -1.0 }, show: [ "scale", "iterations", "fold", "minRadius", "offset", "rotate" ] },
  { id: "soft-sphere", name: "Soft Sphere-Fold", family: 2, category: "boxes", blurb: "A larger min-radius makes rounder, puffier rooms.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 1.9, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.85, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 5.4 }, cam: { dist: 5.4, elev: 0.25, azim: 0.35 }, show: [ "scale", "iterations", "fold", "minRadius", "offset", "rotate" ] },
  { id: "sharp-sphere", name: "Needle Halls", family: 2, category: "boxes", blurb: "A tiny min-radius keeps sharp corners and thin bridges.", params: { power: 8.0, iterations: 9, bailout: 2.0, scale: 2.1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.2, fixedRadius: 1.0, palette: 8, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 5.3 }, cam: { dist: 5.3, elev: 0.32, azim: -0.2 }, show: [ "scale", "iterations", "fold", "minRadius", "offset", "rotate" ] },
  { id: "offset-box", name: "Slid City", family: 2, category: "boxes", blurb: "Slide the seed and the city grows off-kilter.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.0, offsetX: 0.25, offsetY: 0.1, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 3, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 5.6 }, cam: { dist: 5.6, elev: 0.3, azim: 0.6 }, show: [ "scale", "iterations", "fold", "minRadius", "offset", "rotate" ] },
  { id: "spin-box", name: "Twisted Hangar", family: 2, category: "boxes", blurb: "A twist turns hallways into a corkscrew station.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.9, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 2, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 5.5 }, cam: { dist: 5.5, elev: 0.45, azim: -0.55 }, show: [ "scale", "iterations", "fold", "minRadius", "offset", "rotate" ] },
  { id: "amazing-box", name: "Amazing Box", family: 2, category: "boxes", blurb: "A popular scale-and-fold combo that looks like stacked temples.", params: { power: 8.0, iterations: 10, bailout: 2.0, scale: 1.8, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 7, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 110, camDist: 5.0 }, cam: { dist: 5.0, elev: 0.35, azim: 1.2 }, show: [ "scale", "iterations", "fold", "minRadius", "offset", "rotate" ] },
  { id: "box-glow", name: "Neon Warehouse", family: 2, category: "boxes", blurb: "Same box math with neon paint and extra glow.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.05, minRadius: 0.5, fixedRadius: 1.0, palette: 8, glow: 0.9, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 5.4 }, cam: { dist: 5.4, elev: 0.28, azim: 0.15 }, show: [ "scale", "iterations", "fold", "minRadius", "offset", "rotate" ] },
  { id: "shallow-box", name: "Shallow Ruin", family: 2, category: "boxes", blurb: "Few repeats leave big simple blocks \u2014 a ruin, not a maze.", params: { power: 8.0, iterations: 4, bailout: 2.0, scale: 2.2, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 9, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 6.2 }, cam: { dist: 6.2, elev: 0.4, azim: -0.8 }, show: [ "scale", "iterations", "fold", "minRadius", "offset", "rotate" ] },
  { id: "menger-classic", name: "Classic Menger", family: 3, category: "sponges", blurb: "A sponge cube: every face has a window, and those windows have windows.", params: { power: 8.0, iterations: 4, bailout: 2.0, scale: 3.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 9, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.6 }, cam: { dist: 3.6, elev: 0.4, azim: 0.6 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "menger-deep", name: "Deep Menger", family: 3, category: "sponges", blurb: "More cuts. Lace made of cubes.", params: { power: 8.0, iterations: 6, bailout: 2.0, scale: 3.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 2, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 110, camDist: 3.4 }, cam: { dist: 3.4, elev: 0.35, azim: -0.5 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "menger-soft", name: "Chunky Menger", family: 3, category: "sponges", blurb: "Only a couple of cuts. Big friendly holes.", params: { power: 8.0, iterations: 2, bailout: 2.0, scale: 3.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 1, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.8 }, cam: { dist: 3.8, elev: 0.3, azim: 0.2 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "menger-scale", name: "Stretched Sponge", family: 3, category: "sponges", blurb: "A different scale changes hole size versus wall thickness.", params: { power: 8.0, iterations: 5, bailout: 2.0, scale: 2.4, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 7, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.5 }, cam: { dist: 3.5, elev: 0.42, azim: 1.0 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "menger-tilt", name: "Tilted Sponge", family: 3, category: "sponges", blurb: "Spin the cube so you look down a hallway of holes.", params: { power: 8.0, iterations: 4, bailout: 2.0, scale: 3.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.6, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 6, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.5 }, cam: { dist: 3.5, elev: 0.5, azim: -0.3 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "menger-shift", name: "Shifted Lattice", family: 3, category: "sponges", blurb: "Nudge the cube and the holes no longer line up with the world.", params: { power: 8.0, iterations: 4, bailout: 2.0, scale: 3.0, offsetX: 0.2, offsetY: 0.08, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.6 }, cam: { dist: 3.6, elev: 0.28, azim: 0.85 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "menger-tiny", name: "Pocket Sponge", family: 3, category: "sponges", blurb: "Camera closer, slightly different scale \u2014 a desk toy sponge.", params: { power: 8.0, iterations: 5, bailout: 2.0, scale: 2.7, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 0, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.8 }, cam: { dist: 2.8, elev: 0.25, azim: -1.0 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "menger-gold", name: "Gold Lattice", family: 3, category: "sponges", blurb: "Menger bones in gold light.", params: { power: 8.0, iterations: 5, bailout: 2.0, scale: 3.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 7, glow: 0.45, softShadow: 0.85, ao: 0.8, exposure: 1.4, maxSteps: 90, camDist: 3.5 }, cam: { dist: 3.5, elev: 0.38, azim: 0.4 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "tetra-classic", name: "Sierpinski Tetra", family: 4, category: "stars", blurb: "Four corners forever. A pyramid that is all corners.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 5, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.2 }, cam: { dist: 3.2, elev: 0.45, azim: 0.5 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "tetra-deep", name: "Deep Tetra", family: 4, category: "stars", blurb: "More repeats, thinner arms, a spiky star.", params: { power: 8.0, iterations: 12, bailout: 2.0, scale: 2.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 8, glow: 0.55, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.0 }, cam: { dist: 3.0, elev: 0.4, azim: -0.6 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "tetra-soft", name: "Puffy Tetra", family: 4, category: "stars", blurb: "Few repeats leave fat tetrahedral pillows.", params: { power: 8.0, iterations: 4, bailout: 2.0, scale: 2.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.4 }, cam: { dist: 3.4, elev: 0.35, azim: 0.2 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "tetra-scale", name: "Wide Tetra", family: 4, category: "stars", blurb: "A larger scale spreads the four corners farther apart.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.4, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 1, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.5 }, cam: { dist: 3.5, elev: 0.42, azim: 1.1 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "tetra-spin", name: "Spinning Tetra", family: 4, category: "stars", blurb: "Twisted so the points sweep past the camera.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.8, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 0, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.2 }, cam: { dist: 3.2, elev: 0.3, azim: -0.4 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "tetra-shift", name: "Leaning Tetra", family: 4, category: "stars", blurb: "Offset makes one arm thicker than the others.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.0, offsetX: 0.08, offsetY: 0.15, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 3, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.3 }, cam: { dist: 3.3, elev: 0.25, azim: 0.7 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "tetra-ice", name: "Ice Tetra", family: 4, category: "stars", blurb: "Frozen pyramid star.", params: { power: 8.0, iterations: 9, bailout: 2.0, scale: 2.05, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 6, glow: 0.7, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.1 }, cam: { dist: 3.1, elev: 0.48, azim: 0.15 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "kifs-classic", name: "Kaleido IFS", family: 5, category: "stars", blurb: "Mirror, slide, shrink, repeat. A kaleidoscope sculpture.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 1.8, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 0.5, minRadius: 0.5, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.4 }, cam: { dist: 3.4, elev: 0.3, azim: 0.4 }, show: [ "iterations", "scale", "fold", "rotate", "offset", "julia" ] },
  { id: "kifs-flower", name: "Kaleido Flower", family: 5, category: "stars", blurb: "Softer fold and a candy palette \u2014 a stone flower.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 1.65, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 0.72, minRadius: 0.5, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.2 }, cam: { dist: 3.2, elev: 0.22, azim: -0.5 }, show: [ "iterations", "scale", "fold", "rotate", "offset", "julia" ] },
  { id: "kifs-star", name: "Kaleido Star", family: 5, category: "stars", blurb: "Tighter fold makes a pointed star cluster.", params: { power: 8.0, iterations: 9, bailout: 2.0, scale: 1.9, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 0.28, minRadius: 0.5, fixedRadius: 1.0, palette: 5, glow: 0.55, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.1 }, cam: { dist: 3.1, elev: 0.35, azim: 0.9 }, show: [ "iterations", "scale", "fold", "rotate", "offset", "julia" ] },
  { id: "kifs-cube", name: "Kaleido Cube", family: 5, category: "stars", blurb: "Scale near 2 with a boxy fold. A jeweled cube.", params: { power: 8.0, iterations: 7, bailout: 2.0, scale: 2.05, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 0.55, minRadius: 0.5, fixedRadius: 1.0, palette: 7, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.6 }, cam: { dist: 3.6, elev: 0.4, azim: -0.2 }, show: [ "iterations", "scale", "fold", "rotate", "offset", "julia" ] },
  { id: "kifs-snow", name: "Kaleido Snow", family: 5, category: "stars", blurb: "Icy colors and a small fold, like a 3-D snowflake.", params: { power: 8.0, iterations: 10, bailout: 2.0, scale: 1.75, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 0.4, minRadius: 0.5, fixedRadius: 1.0, palette: 6, glow: 0.7, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.0 }, cam: { dist: 3.0, elev: 0.45, azim: 0.25 }, show: [ "iterations", "scale", "fold", "rotate", "offset", "julia" ] },
  { id: "kifs-spine", name: "Kaleido Spine", family: 5, category: "stars", blurb: "A julia nudge stretches one axis into a spine.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 1.85, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.6, juliaY: 0.0, juliaZ: 0.0, fold: 0.45, minRadius: 0.5, fixedRadius: 1.0, palette: 8, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.3 }, cam: { dist: 3.3, elev: 0.2, azim: 1.2 }, show: [ "iterations", "scale", "fold", "rotate", "offset", "julia" ] },
  { id: "kifs-nest", name: "Kaleido Nest", family: 5, category: "stars", blurb: "Many repeats nest rooms inside rooms.", params: { power: 8.0, iterations: 12, bailout: 2.0, scale: 1.7, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 0.5, minRadius: 0.5, fixedRadius: 1.0, palette: 2, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 110, camDist: 3.0 }, cam: { dist: 3.0, elev: 0.32, azim: -0.8 }, show: [ "iterations", "scale", "fold", "rotate", "offset", "julia" ] },
  { id: "kifs-crown", name: "Kaleido Crown", family: 5, category: "stars", blurb: "High fold + gold. A crown of mirrors.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 1.95, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 0.85, minRadius: 0.5, fixedRadius: 1.0, palette: 7, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.5 }, cam: { dist: 3.5, elev: 0.38, azim: 0.55 }, show: [ "iterations", "scale", "fold", "rotate", "offset", "julia" ] },
  { id: "kifs-web", name: "Kaleido Web", family: 5, category: "stars", blurb: "Thin scale and neon \u2014 a glowing web.", params: { power: 8.0, iterations: 9, bailout: 2.0, scale: 1.55, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 0.33, minRadius: 0.5, fixedRadius: 1.0, palette: 8, glow: 0.8, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.1 }, cam: { dist: 3.1, elev: 0.18, azim: -1.1 }, show: [ "iterations", "scale", "fold", "rotate", "offset", "julia" ] },
  { id: "kifs-spin", name: "Kaleido Twist", family: 5, category: "stars", blurb: "Extra rotate so the mirrors never sit square.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 1.8, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 1.1, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 0.5, minRadius: 0.5, fixedRadius: 1.0, palette: 0, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.3 }, cam: { dist: 3.3, elev: 0.28, azim: 0.1 }, show: [ "iterations", "scale", "fold", "rotate", "offset", "julia" ] },
  { id: "hybrid-boxbulb", name: "Box + Bulb", family: 6, category: "hybrids", blurb: "Box folds first, then a bulb. A city that grew a brain.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.1, juliaY: 0.2, juliaZ: 0.1, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 0, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.2 }, cam: { dist: 3.2, elev: 0.25, azim: 0.4 }, show: [ "power", "iterations", "scale", "fold", "julia", "offset", "rotate" ] },
  { id: "hybrid-folded", name: "Folded Bulb", family: 6, category: "hybrids", blurb: "Stronger fold, milder power. Ribbed fruit.", params: { power: 6, iterations: 8, bailout: 2.0, scale: 1.05, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.15, juliaZ: 0.0, fold: 1.35, minRadius: 0.5, fixedRadius: 1.0, palette: 1, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.0 }, cam: { dist: 3.0, elev: 0.3, azim: -0.6 }, show: [ "power", "iterations", "scale", "fold", "julia", "offset", "rotate" ] },
  { id: "hybrid-sphere", name: "Sphere-Fold Bulb", family: 6, category: "hybrids", blurb: "Scale a bit over 1. Inverted shells around a bulb.", params: { power: 8, iterations: 7, bailout: 2.0, scale: 1.25, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.1, juliaY: 0.05, juliaZ: 0.2, fold: 0.9, minRadius: 0.5, fixedRadius: 1.0, palette: 2, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.1 }, cam: { dist: 3.1, elev: 0.2, azim: 0.9 }, show: [ "power", "iterations", "scale", "fold", "julia", "offset", "rotate" ] },
  { id: "hybrid-city", name: "City Bulb", family: 6, category: "hybrids", blurb: "More box, less bulb. Towers with organic caps.", params: { power: 4, iterations: 9, bailout: 2.0, scale: 1.4, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.2, juliaY: -0.1, juliaZ: 0.05, fold: 1.1, minRadius: 0.5, fixedRadius: 1.0, palette: 9, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.6 }, cam: { dist: 3.6, elev: 0.4, azim: -0.3 }, show: [ "power", "iterations", "scale", "fold", "julia", "offset", "rotate" ] },
  { id: "hybrid-alien", name: "Alien Hybrid", family: 6, category: "hybrids", blurb: "Odd seed and neon paint. A visitor.", params: { power: 9, iterations: 8, bailout: 2.0, scale: 0.95, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.35, juliaY: 0.35, juliaZ: -0.2, fold: 0.75, minRadius: 0.5, fixedRadius: 1.0, palette: 8, glow: 0.7, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.9 }, cam: { dist: 2.9, elev: 0.22, azim: 1.15 }, show: [ "power", "iterations", "scale", "fold", "julia", "offset", "rotate" ] },
  { id: "hybrid-soft", name: "Soft Hybrid", family: 6, category: "hybrids", blurb: "Low power, gentle fold. Melted architecture.", params: { power: 3, iterations: 8, bailout: 2.0, scale: 1.1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.05, juliaY: 0.25, juliaZ: 0.05, fold: 1.2, minRadius: 0.5, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.3 }, cam: { dist: 3.3, elev: 0.18, azim: 0.2 }, show: [ "power", "iterations", "scale", "fold", "julia", "offset", "rotate" ] },
  { id: "hybrid-spiky", name: "Spiky Hybrid", family: 6, category: "hybrids", blurb: "High power punches spikes through the folds.", params: { power: 12, iterations: 7, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.12, juliaY: 0.0, juliaZ: 0.18, fold: 0.85, minRadius: 0.5, fixedRadius: 1.0, palette: 5, glow: 0.6, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.8 }, cam: { dist: 2.8, elev: 0.3, azim: -0.85 }, show: [ "power", "iterations", "scale", "fold", "julia", "offset", "rotate" ] },
  { id: "hybrid-nested", name: "Nested Hybrid", family: 6, category: "hybrids", blurb: "Lots of repeats nest bulbs inside boxes.", params: { power: 8, iterations: 12, bailout: 2.0, scale: 1.05, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.08, juliaY: 0.12, juliaZ: 0.08, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 6, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 120, camDist: 3.0 }, cam: { dist: 3.0, elev: 0.35, azim: 0.55 }, show: [ "power", "iterations", "scale", "fold", "julia", "offset", "rotate" ] },
  { id: "hybrid-neg", name: "Inverted Hybrid", family: 6, category: "hybrids", blurb: "Negative scale flips the hybrid inside-out.", params: { power: 8, iterations: 8, bailout: 2.0, scale: -1.2, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.15, juliaY: 0.1, juliaZ: 0.15, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 0, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.4 }, cam: { dist: 3.4, elev: 0.28, azim: -0.15 }, show: [ "power", "iterations", "scale", "fold", "julia", "offset", "rotate" ] },
  { id: "quat-classic", name: "Quaternion Julia", family: 7, category: "worlds", blurb: "A 4-D Julia sliced into 3-D. Smooth, glassy, and a little alien.", params: { power: 8.0, iterations: 9, bailout: 4, scale: 1, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.2, juliaY: 0.6, juliaZ: 0.2, fold: 1.0, minRadius: 0.0, fixedRadius: 1.0, palette: 2, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.6 }, cam: { dist: 2.6, elev: 0.2, azim: 0.4 }, show: [ "iterations", "bailout", "julia", "scale", "minRadius", "rotate" ] },
  { id: "quat-twist", name: "Quat Twist", family: 7, category: "worlds", blurb: "A twistier seed, more ribbons than blobs.", params: { power: 8.0, iterations: 9, bailout: 4, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.3, juliaY: 0.5, juliaZ: -0.25, fold: 1.0, minRadius: 0.1, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.5 }, cam: { dist: 2.5, elev: 0.28, azim: -0.7 }, show: [ "iterations", "bailout", "julia", "scale", "minRadius", "rotate" ] },
  { id: "quat-ribbon", name: "Quat Ribbon", family: 7, category: "worlds", blurb: "Thin w-slice (min radius) cuts ribbons from the 4-D cloud.", params: { power: 8.0, iterations: 10, bailout: 4, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.4, juliaY: 0.2, juliaZ: 0.4, fold: 1.0, minRadius: 0.35, fixedRadius: 1.0, palette: 8, glow: 0.55, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.4 }, cam: { dist: 2.4, elev: 0.15, azim: 1.0 }, show: [ "iterations", "bailout", "julia", "scale", "minRadius", "rotate" ] },
  { id: "quat-crystal", name: "Quat Crystal", family: 7, category: "worlds", blurb: "Icy seed. Looks grown in a cave.", params: { power: 8.0, iterations: 9, bailout: 4, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.1, juliaY: -0.55, juliaZ: 0.15, fold: 1.0, minRadius: 0.0, fixedRadius: 1.0, palette: 6, glow: 0.5, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.55 }, cam: { dist: 2.55, elev: 0.35, azim: 0.2 }, show: [ "iterations", "bailout", "julia", "scale", "minRadius", "rotate" ] },
  { id: "quat-cloud", name: "Quat Cloud", family: 7, category: "worlds", blurb: "A mild seed and fewer repeats \u2014 a puffy cloud island.", params: { power: 8.0, iterations: 6, bailout: 6, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.15, juliaY: 0.35, juliaZ: 0.1, fold: 1.0, minRadius: 0.0, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.9 }, cam: { dist: 2.9, elev: 0.18, azim: -0.4 }, show: [ "iterations", "bailout", "julia", "scale", "minRadius", "rotate" ] },
  { id: "quat-needle", name: "Quat Needle", family: 7, category: "worlds", blurb: "Seed near the edge. Long needles and thin bridges.", params: { power: 8.0, iterations: 10, bailout: 4, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.55, juliaY: 0.4, juliaZ: 0.05, fold: 1.0, minRadius: 0.2, fixedRadius: 1.0, palette: 5, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.45 }, cam: { dist: 2.45, elev: 0.25, azim: 0.75 }, show: [ "iterations", "bailout", "julia", "scale", "minRadius", "rotate" ] },
  { id: "quat-gold", name: "Quat Relic", family: 7, category: "worlds", blurb: "Gold glass quaternion.", params: { power: 8.0, iterations: 9, bailout: 4, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.25, juliaY: 0.45, juliaZ: 0.3, fold: 1.0, minRadius: 0.05, fixedRadius: 1.0, palette: 7, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.4, maxSteps: 90, camDist: 2.5 }, cam: { dist: 2.5, elev: 0.3, azim: -1.0 }, show: [ "iterations", "bailout", "julia", "scale", "minRadius", "rotate" ] },
  { id: "quat-ink", name: "Ink Quat", family: 7, category: "worlds", blurb: "Monochrome so the sculpture is the star.", params: { power: 8.0, iterations: 9, bailout: 4, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.2, juliaY: -0.4, juliaZ: 0.35, fold: 1.0, minRadius: 0.0, fixedRadius: 1.0, palette: 9, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.55 }, cam: { dist: 2.55, elev: 0.22, azim: 0.55 }, show: [ "iterations", "bailout", "julia", "scale", "minRadius", "rotate" ] },
  { id: "apollo-classic", name: "Apollonian Foam", family: 8, category: "worlds", blurb: "Spheres packed in spheres. Bubble foam that never ends.", params: { power: 8.0, iterations: 7, bailout: 2.0, scale: 1.8, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 2, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.4 }, cam: { dist: 2.4, elev: 0.25, azim: 0.5 }, show: [ "iterations", "scale", "fold", "offset", "rotate" ] },
  { id: "apollo-deep", name: "Deep Foam", family: 8, category: "worlds", blurb: "More inversions, tinier bubbles in the gaps.", params: { power: 8.0, iterations: 10, bailout: 2.0, scale: 1.9, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 6, glow: 0.5, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 110, camDist: 2.2 }, cam: { dist: 2.2, elev: 0.3, azim: -0.4 }, show: [ "iterations", "scale", "fold", "offset", "rotate" ] },
  { id: "apollo-soft", name: "Soft Foam", family: 8, category: "worlds", blurb: "Fewer inversions \u2014 big friendly bubbles.", params: { power: 8.0, iterations: 4, bailout: 2.0, scale: 1.6, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.1, minRadius: 0.5, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.6 }, cam: { dist: 2.6, elev: 0.2, azim: 0.2 }, show: [ "iterations", "scale", "fold", "offset", "rotate" ] },
  { id: "apollo-tight", name: "Tight Pack", family: 8, category: "worlds", blurb: "Higher scale packs spheres tighter.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.3, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 0.85, minRadius: 0.5, fixedRadius: 1.0, palette: 8, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.3 }, cam: { dist: 2.3, elev: 0.35, azim: 0.9 }, show: [ "iterations", "scale", "fold", "offset", "rotate" ] },
  { id: "apollo-wide", name: "Wide Foam", family: 8, category: "worlds", blurb: "Wide fold opens bigger caverns between bubbles.", params: { power: 8.0, iterations: 7, bailout: 2.0, scale: 1.7, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.4, minRadius: 0.5, fixedRadius: 1.0, palette: 0, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.7 }, cam: { dist: 2.7, elev: 0.28, azim: -0.8 }, show: [ "iterations", "scale", "fold", "offset", "rotate" ] },
  { id: "apollo-gold", name: "Gold Bubbles", family: 8, category: "worlds", blurb: "Apollonian foam in gold.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 1.85, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 7, glow: 0.45, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.35 }, cam: { dist: 2.35, elev: 0.32, azim: 0.15 }, show: [ "iterations", "scale", "fold", "offset", "rotate" ] },
  { id: "octa-classic", name: "Octahedral Star", family: 9, category: "stars", blurb: "Eight-sided kaleidoscope. A crystal star.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 6, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.2 }, cam: { dist: 3.2, elev: 0.4, azim: 0.45 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "octa-deep", name: "Deep Octa", family: 9, category: "stars", blurb: "More repeats carve a lacy octahedron.", params: { power: 8.0, iterations: 12, bailout: 2.0, scale: 2.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 8, glow: 0.55, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.0 }, cam: { dist: 3.0, elev: 0.35, azim: -0.5 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "octa-chunk", name: "Chunky Octa", family: 9, category: "stars", blurb: "Few repeats, fat crystals.", params: { power: 8.0, iterations: 4, bailout: 2.0, scale: 2.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 7, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.4 }, cam: { dist: 3.4, elev: 0.3, azim: 0.2 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "octa-wide", name: "Wide Octa", family: 9, category: "stars", blurb: "Larger scale spreads the points.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.4, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 1, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.5 }, cam: { dist: 3.5, elev: 0.42, azim: 1.0 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "octa-spin", name: "Twisted Octa", family: 9, category: "stars", blurb: "Rotated so edges sweep past you.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.85, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 0, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.2 }, cam: { dist: 3.2, elev: 0.28, azim: -0.3 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "octa-shift", name: "Leaning Octa", family: 9, category: "stars", blurb: "Offset fattens one side of the star.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 2.0, offsetX: 0.12, offsetY: -0.08, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.3 }, cam: { dist: 3.3, elev: 0.25, azim: 0.7 }, show: [ "iterations", "scale", "offset", "rotate" ] },
  { id: "ship-classic", name: "Burning Ship 3D", family: 10, category: "hybrids", blurb: "Take absolute values before folding. A ship of spikes.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.45, juliaY: 0.55, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 5, glow: 0.5, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.5 }, cam: { dist: 2.5, elev: 0.2, azim: 0.5 }, show: [ "power", "iterations", "bailout", "julia", "offset", "rotate" ] },
  { id: "ship-soft", name: "Soft Ship", family: 10, category: "hybrids", blurb: "Lower power, gentler hull.", params: { power: 4, iterations: 9, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.3, juliaY: 0.4, juliaZ: 0.1, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 1, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.7 }, cam: { dist: 2.7, elev: 0.18, azim: -0.6 }, show: [ "power", "iterations", "bailout", "julia", "offset", "rotate" ] },
  { id: "ship-spiky", name: "Spiky Ship", family: 10, category: "hybrids", blurb: "High power, a hull of needles.", params: { power: 12, iterations: 7, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.2, juliaY: 0.6, juliaZ: 0.15, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 5, glow: 0.75, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.3 }, cam: { dist: 2.3, elev: 0.25, azim: 0.9 }, show: [ "power", "iterations", "bailout", "julia", "offset", "rotate" ] },
  { id: "abs-bulb", name: "Mirror Bulb", family: 10, category: "hybrids", blurb: "Absolute-value bulb with a mild seed \u2014 mirrored lobes.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.15, juliaY: 0.1, juliaZ: 0.2, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 0, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.6 }, cam: { dist: 2.6, elev: 0.3, azim: -0.2 }, show: [ "power", "iterations", "bailout", "julia", "offset", "rotate" ] },
  { id: "abs-candy", name: "Candy Ship", family: 10, category: "hybrids", blurb: "Candy colors on a burning-ship body.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.35, juliaY: 0.35, juliaZ: 0.2, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 4, glow: 0.55, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.55 }, cam: { dist: 2.55, elev: 0.22, azim: 1.1 }, show: [ "power", "iterations", "bailout", "julia", "offset", "rotate" ] },
  { id: "abs-ice", name: "Ice Ship", family: 10, category: "hybrids", blurb: "Frozen masts and glowing fog.", params: { power: 8, iterations: 9, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.25, juliaY: 0.5, juliaZ: -0.1, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 6, glow: 0.7, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.45 }, cam: { dist: 2.45, elev: 0.35, azim: -0.85 }, show: [ "power", "iterations", "bailout", "julia", "offset", "rotate" ] },
  { id: "abs-p2", name: "Abs Peanut", family: 10, category: "hybrids", blurb: "Power 2 plus mirrors \u2014 a bent peanut.", params: { power: 2, iterations: 12, bailout: 4, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: -0.5, juliaY: 0.3, juliaZ: 0.1, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 3, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.9 }, cam: { dist: 2.9, elev: 0.12, azim: 0.3 }, show: [ "power", "iterations", "bailout", "julia", "offset", "rotate" ] },
  { id: "klein-classic", name: "Pseudo Kleinian", family: 11, category: "worlds", blurb: "Box clamps plus inversions. A foamy limit set.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 1.5, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 2, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.0 }, cam: { dist: 3.0, elev: 0.3, azim: 0.45 }, show: [ "iterations", "scale", "fold", "minRadius", "offset", "rotate" ] },
  { id: "klein-foam", name: "Klein Foam", family: 11, category: "worlds", blurb: "More repeats, finer foam.", params: { power: 8.0, iterations: 11, bailout: 2.0, scale: 1.55, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.45, fixedRadius: 1.0, palette: 6, glow: 0.5, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 110, camDist: 2.8 }, cam: { dist: 2.8, elev: 0.35, azim: -0.4 }, show: [ "iterations", "scale", "fold", "minRadius", "offset", "rotate" ] },
  { id: "klein-wide", name: "Wide Klein", family: 11, category: "worlds", blurb: "Wide fold opens big rooms in the foam.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 1.4, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.45, minRadius: 0.5, fixedRadius: 1.0, palette: 0, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.4 }, cam: { dist: 3.4, elev: 0.28, azim: 0.8 }, show: [ "iterations", "scale", "fold", "minRadius", "offset", "rotate" ] },
  { id: "klein-tight", name: "Tight Klein", family: 11, category: "worlds", blurb: "Small fold and higher scale \u2014 dense lace.", params: { power: 8.0, iterations: 9, bailout: 2.0, scale: 1.7, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 0.7, minRadius: 0.35, fixedRadius: 1.0, palette: 8, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.7 }, cam: { dist: 2.7, elev: 0.32, azim: -0.9 }, show: [ "iterations", "scale", "fold", "minRadius", "offset", "rotate" ] },
  { id: "klein-gold", name: "Gold Klein", family: 11, category: "worlds", blurb: "Limit-set foam in gold.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 1.5, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.05, minRadius: 0.5, fixedRadius: 1.0, palette: 7, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.35, maxSteps: 90, camDist: 3.0 }, cam: { dist: 3.0, elev: 0.4, azim: 0.2 }, show: [ "iterations", "scale", "fold", "minRadius", "offset", "rotate" ] },
  { id: "klein-shift", name: "Drift Klein", family: 11, category: "worlds", blurb: "Offset slides the whole foam off-center.", params: { power: 8.0, iterations: 8, bailout: 2.0, scale: 1.5, offsetX: 0.2, offsetY: 0.0, offsetZ: 0.12, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 4, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 3.1 }, cam: { dist: 3.1, elev: 0.24, azim: 1.0 }, show: [ "iterations", "scale", "fold", "minRadius", "offset", "rotate" ] },
  { id: "tetra-brot", name: "Tetrabrot", family: 12, category: "stars", blurb: "Tetrahedral mirrors plus a bulb. A star that also dimples.", params: { power: 8, iterations: 8, bailout: 2, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 5, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.7 }, cam: { dist: 2.7, elev: 0.35, azim: 0.4 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "tetra-brot-soft", name: "Soft Tetrabrot", family: 12, category: "stars", blurb: "Low power tetrabrot. Chubby star-fruit.", params: { power: 4, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 1, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.9 }, cam: { dist: 2.9, elev: 0.28, azim: -0.5 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "tetra-brot-spike", name: "Spiky Tetrabrot", family: 12, category: "stars", blurb: "High power, a four-cornered urchin.", params: { power: 12, iterations: 7, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 8, glow: 0.65, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.5 }, cam: { dist: 2.5, elev: 0.3, azim: 0.8 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "tetra-brot-deep", name: "Deep Tetrabrot", family: 12, category: "stars", blurb: "More repeats etch finer tetrahedral cracks.", params: { power: 8, iterations: 12, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 6, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 110, camDist: 2.6 }, cam: { dist: 2.6, elev: 0.4, azim: -0.25 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "tetra-brot-tilt", name: "Tilted Tetrabrot", family: 12, category: "stars", blurb: "Twisted tetrabrot so a point faces you.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.75, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 0, glow: 0.35, softShadow: 0.85, ao: 0.8, exposure: 1.25, maxSteps: 90, camDist: 2.7 }, cam: { dist: 2.7, elev: 0.22, azim: 1.1 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] },
  { id: "tetra-brot-gold", name: "Gold Tetrabrot", family: 12, category: "stars", blurb: "A relic star.", params: { power: 8, iterations: 8, bailout: 2.0, scale: 1.0, offsetX: 0.0, offsetY: 0.0, offsetZ: 0.0, rotate: 0.0, juliaX: 0.0, juliaY: 0.0, juliaZ: 0.0, fold: 1.0, minRadius: 0.5, fixedRadius: 1.0, palette: 7, glow: 0.5, softShadow: 0.85, ao: 0.8, exposure: 1.4, maxSteps: 90, camDist: 2.65 }, cam: { dist: 2.65, elev: 0.32, azim: 0.15 }, show: [ "power", "iterations", "bailout", "scale", "offset", "rotate" ] }
];

export function getById(id) {
  return CATALOG.find((f) => f.id === id) || CATALOG[0];
}

export function getIndex(id) {
  const i = CATALOG.findIndex((f) => f.id === id);
  return i < 0 ? 0 : i;
}

export function filterCatalog(query, category) {
  const q = (query || "").trim().toLowerCase();
  return CATALOG.filter((f) => {
    if (category && category !== "all" && f.category !== category) return false;
    if (!q) return true;
    return (
      f.name.toLowerCase().includes(q) ||
      f.id.toLowerCase().includes(q) ||
      f.blurb.toLowerCase().includes(q) ||
      f.category.toLowerCase().includes(q)
    );
  });
}

